before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/escaletech/ec2connect/cmd.version={{.Version}} -X github.com/escaletech/ec2connect/cmd.commit={{.ShortCommit}} -X github.com/escaletech/ec2connect/cmd.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: ec2connect
    homepage: https://github.com/escaletech/ec2connect
    maintainer: Escale Digital <dev@escale.com.br>
    description: ec2connect is a convenient SSH wrapper around EC2 instance connect
    formats:
      - deb
brews:
  -
    tap:
      owner: escaletech
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: CI Bot
      email: dev@escale.com.br
    homepage: https://github.com/escaletech/ec2connect
    description: ec2connect is a convenient SSH wrapper around EC2 instance connect
